import { pizzasIngredientList } from "./ingredientList";

export const dishList = [
  {name: "Carbonara", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/04/%D0%9A%D0%B0%D1%80%D0%B1%D0%BE%D0%BD%D0%B0%D1%80%D0%B0_300dpi-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.onion, pizzasIngredientList.bacon, pizzasIngredientList.ham, pizzasIngredientList.mozzarella, pizzasIngredientList.mushrooms, pizzasIngredientList.souseAlfredo], category: "Pizza"},
  {name: "Texas", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/03/%D0%A2%D0%B5%D1%85%D0%B0%D1%81_300dpi-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.corn, pizzasIngredientList.onion, pizzasIngredientList.mushrooms, pizzasIngredientList.bavarianSausages, pizzasIngredientList.mozzarella, pizzasIngredientList.souseBBQ], category: "Pizza"},
  {name: "Vegan", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/04/%D0%BE%D0%B2%D0%BE%D1%87%D1%8D%D0%B2%D0%B0_%D1%84%D1%8D%D0%B5%D1%80%D0%B8%D1%8F_300dpi-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.bellPepper, pizzasIngredientList.olives, pizzasIngredientList.onion, pizzasIngredientList.mushrooms, pizzasIngredientList.tomatoes, pizzasIngredientList.mozzarella, pizzasIngredientList.creamSouse], category: "Pizza"},
  {name: "Mushroom Pizza", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2021/07/27/Manhatten_slice_collageweb-min-thumbnail-960x960-70.jpg', price: '25$', ingredients: [pizzasIngredientList.mushrooms, pizzasIngredientList.tomatoes, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Pizza"},
  {name: "Pepperoni", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_mobile/2018/02/28/%D0%9F%D0%B5%D0%BF%D0%BF%D0%B5%D1%80%D0%BE%D0%BD%D0%B8_%D0%B8_%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D1%8B_300dpi-thumbnail-960x960-70.jpg',price: "1S", ingredients: [pizzasIngredientList.pepperoni, pizzasIngredientList.tomatoes, pizzasIngredientList.mozzarella, pizzasIngredientList.souseBBQ], category: "Pizza"},
  {name: "Margarita", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/04/%D0%9C%D0%B0%D1%80%D0%B3%D0%B0%D1%80%D0%B8%D1%82%D0%B0_300dpi-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.mozzarella, pizzasIngredientList.creamSouse], category: "Pizza"},
  {name: "Grill Mix", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2021/07/27/Grill_slice_collageweb-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.chicken, pizzasIngredientList.onion, pizzasIngredientList.bacon, pizzasIngredientList.bellPepper, pizzasIngredientList.mozzarella, pizzasIngredientList.souseBBQ], category: "Pizza"},
  {name: "Hawaii", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/04/%D0%93%D0%B0%D0%B2%D0%B0%D0%B9%D1%81%D1%8C%D0%BA%D0%B0_300dpi-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.pineapple, pizzasIngredientList.chicken, pizzasIngredientList.corn, pizzasIngredientList.creamSouse], category: "Pizza"},
  {name: "BBQ", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/04/BBQ_DeLUX_300dpi-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.chicken, pizzasIngredientList.onion, pizzasIngredientList.bellPepper, pizzasIngredientList.mozzarella, pizzasIngredientList.mushrooms, pizzasIngredientList.pepperoni, pizzasIngredientList.souseBBQ], category: "Pizza"},
  {name: "Country", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/04/%D0%9A%D0%B0%D0%BD%D1%82%D1%80%D0%B8_300dpi-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.onion, pizzasIngredientList.mushrooms, pizzasIngredientList.bacon, pizzasIngredientList.mozzarella, pizzasIngredientList.ham, pizzasIngredientList.cucumbers, pizzasIngredientList.souseAlfredo], category: "Pizza"},
  {name: "Spicy", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/03/%D0%A1%D0%BF%D0%B0%D0%B9%D1%81%D0%B8_300dpi-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.jalapeno, pizzasIngredientList.bacon, pizzasIngredientList.mozzarella, pizzasIngredientList.pepperoni, pizzasIngredientList.tomatoes, pizzasIngredientList.souseBBQ], category: "Pizza"},
  {name: "Philadelphia", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2019/10/03/SalmonPhill-slicere-made-web-min-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Pizza"},
  {name: "Spinach salad", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/04/03/%D0%A1%D0%B0%D0%BB%D0%B0%D1%82_%D1%81%D0%BE_%D1%88%D0%BF%D0%B8%D0%BD%D0%B0%D1%82%D0%BE%D0%BC-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Salad"},
  {name: "Chicken salad", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/04/03/%D0%A1%D0%B0%D0%BB%D0%B0%D1%82_%D1%81_%D0%BA%D1%83%D1%80%D0%B8%D1%86%D0%B5%D0%B9-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Salad"},
  {name: "Salad with tuna", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/04/03/%D0%A1%D0%B0%D0%BB%D0%B0%D1%82_%D1%81_%D1%82%D1%83%D0%BD%D1%86%D0%BE%D0%BC-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Salad"},
  {name: "Mozzarella salad", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2020/07/22/Salad_MozzarellaTomat_web-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Salad"},
  {name: "Chocolate rolls", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/03/23/ChocoRolltarelka-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Desert"},
  {name: "Vanilla muffin", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/03/23/white_maffin-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Desert"},
  {name: "Chocolate muffin", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/03/23/black_maffin-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Desert"},
  {name: "Chocolate fondant", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/03/23/%D0%BB%D0%B0%D0%B2%D0%B0_%D0%BA%D0%B5%D0%B9%D0%BA-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Desert"},
  {name: "Cinnamon Bites", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/03/30/%D0%91%D0%B0%D0%B9%D1%82%D1%81%D1%8B_%D1%81_%D0%BA%D0%BE%D1%80%D0%B8%D1%86%D0%B5%D0%B9-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Desert"},
  {name: "Country style potatoes", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image/2018/04/03/%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D0%BF%D0%BB%D1%8F%D0%BD%D1%96_%D1%88%D0%BC%D0%B0%D1%82%D0%BE%D1%87%D0%BA%D0%B8-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Potato"},
  {name: "French fries", img: 'https://media.dominos.ua/__sized__/menu/product_osg_image_category/2021/07/27/Fri_potato_Dominosweb-min-thumbnail-960x960-70.jpg', price: "50$", ingredients: [pizzasIngredientList.salmon, pizzasIngredientList.creamSouse, pizzasIngredientList.souseAlfredo, pizzasIngredientList.mozzarella], category: "Potato"},

]
